### ISSUE TITLE
Adding elm navigation?

### ISSUE THREAD

**Issue by JordyMoos** [JordyMoos/elm-yapm-client#72]
At the moment everything is on one url.
If we add elm navigation we would gain these points:

### Every page gets his own url

- Unauth = /
- Auth Main = /
- Auth edit = /edit/:id
- etc

This does not really add something useful for our protected app. But does looks nicer i guess.
This also means that the modal will be removed for the add and edits.
They can stay for the confirmation.

### Auth Main will be split up

The part where all Msg's etc will be routed to the appropriate sub page (edit, add, master key etc)
And there will be a "List or Index or Search" page where the logic lives for listing and filtering on the passwords. (This will make the code cleaner i guess)

**Comment by marcusklaas** [comment]
There is no harm in doing this, I guess. But I doubt the added utility. We don't really need to save the state in the URL, since we'll always have to reauthenticate whenever we come back to the page. The app also isn't very suited to sharing, for obvious reasons ;-)

I'd consider this a low priority issue. But it could be fun/ educational to implement.

**Comment by JordyMoos** [comment]
I agree we don't need the Navigation. 
But it is learning full and won't do any harm. It even might force the code even more to the standards
